### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/working-group-bylaws#2]
The code of conduct should be officialised at the next official meeting

**Comment by jbelien** [comment]
I propose to do it at next meetup in Brussels on 16/10/2017 :)

**Comment by joostschouppe** [comment]
Yes, but then we should put it in the agenda and communicate it two weeks in advance.

**Comment by jbelien** [comment]
Yes!
I was planning to send an email on our mailinglist, I'll try not to forget to mention the code of conduct!

**Comment by jbelien** [comment]
Will be voted on 13.12.2018 official meeting !
